import Bridge from '@expressms/smartapp-bridge'
import {
  cleanCache,
  clientStorageClear,
  clientStorageGet,
  clientStorageRemove,
  clientStorageSet,
  createDeeplink,
  getAppVisibility,
  getChats,
  getConnectionStatus,
  getLayoutType,
  getSmartAppList,
  getUnreadCounter,
  handleDeeplink,
  openChatMessage,
  openClientSettings,
  openGroupChat,
  requestLocation,
  searchCorporatePhonebook,
  searchLocalPhonebook,
  sendBotCommand,
  setWebResourceCookies,
  subscribeClientEvents,
  unsubscribeClientEvents,
} from './lib/client'
import { openFile, uploadFile, uploadFiles } from './lib/client/file'
import {
  addContact,
  createPersonalChat,
  getContact,
  openContactCard,
  openPersonalChat,
  requestSelfProfile,
  sendMessage,
} from './lib/contacts'
import { useQuery } from './lib/helpers/helpers'
import { ready } from './lib/logging'
import { onNotification } from './lib/notification'
import {
  closeSmartApp,
  exitSmartAppToCatalog,
  onBackPressed,
  onMoveToRoot,
  openSmartApp,
  routingChanged,
} from './lib/routing'

export {
  Bridge,
  ready,
  routingChanged,
  onBackPressed,
  addContact,
  getContact,
  createPersonalChat,
  onNotification,
  sendMessage,
  openSmartApp,
  openFile,
  uploadFile,
  uploadFiles,
  exitSmartAppToCatalog,
  useQuery,
  openClientSettings,
  getChats,
  searchCorporatePhonebook,
  sendBotCommand,
  openGroupChat,
  onMoveToRoot,
  requestLocation,
  openContactCard,
  requestSelfProfile,
  closeSmartApp,
  getAppVisibility,
  getConnectionStatus,
  subscribeClientEvents,
  unsubscribeClientEvents,
  createDeeplink,
  openChatMessage,
  clientStorageGet,
  clientStorageSet,
  clientStorageRemove,
  clientStorageClear,
  openPersonalChat,
  handleDeeplink,
  searchLocalPhonebook,
  getUnreadCounter,
  getLayoutType,
  cleanCache,
  getSmartAppList,
  setWebResourceCookies,
}
